version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.1

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          mapping: |
            user/.* build-user true
            world/.* build-world true
          base-revision: origin/master
